### ISSUE TITLE
preserve the 'User' folder if installing on-top of an existing installation

### ISSUE THREAD

**Issue by Kerbtree** [MostlyWhat/128Bit-Yuzu-Installer#19]
Hi, can the installer be made to check for (and preserve) a "User" folder inside the install location? This is where a portable installation of Yuzu stores settings, NAND etc. The installer just blew mine up, nothing in Recycle Bin.

**Comment by GlaZedBelmont** [comment]
Consider https://github.com/MostlyWhat/128Bit-Yuzu-Installer/issues/8
Which was never fixed. Be glad you didn't select an important folder

**Comment by MostlyWhat** [comment]
True, the installer framework isn't mine, and I never install the program and data files together.

**Comment by MostlyWhat** [comment]
I will try to do this, but please suggest me the ways the program can perform this. @GlaZedBelmont @Kerbtree

**Comment by MostlyWhat** [comment]
Implementing in #21
