### ISSUE TITLE
Portable support - install locations and shortcut names and locations

### ISSUE THREAD

**Issue by JaxJaxW** [MostlyWhat/128Bit-Yuzu-Installer#20]
Hello!

I was reading https://github.com/Abd-007/Switch-Emulators-Guide/blob/main/Yuzu.md which is a great guide and it mentions this nice tool that appears to be able to update the Yuzu EA branch for me which is awesome. I love the look, color, and supported functionality of the tool. As it is the tool works great and gives me the latest version without a problem. However, I'd like to request portable support on Windows for this application which would just make it perfect.

Currently, it installs Yuzu EA in yuzu-early-access wherever the maintenancetool.exe is. I would love it if in advanced settings I could choose the directory for both the Yuzu EA and the maintenance tool. I prefer to make my yuzu installation portable and save it in "C:\Emulators\Yuzu EA (Switch)" and I prefer to save tools like these in "C:\Emulators\Tools\".

In addition, I would like to be able to rename the shortcut link names to "Yuzu EA (Switch)" and "Yuzu EA Updater". That currently seems possible to change within the metadata.json by changing the filepaths but I haven't figured out a way to confirm it. Clicking update at least doesn't override my custom paths. Also manually changing the name of the maintenance tool to "Yuzu EA Updater.exe" appears to at least automatically change the name of the shortcut which is nice. Interestingly on clicking repair, it resets my custom yuzu EA shortcut path to the default but keeps my custom "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Yuzu EA Updater.lnk" path. I prefer to keep all of my shortcuts named and in the same place, so I prefer this Start Menu directory over the default "C:\Users\Jaxton\AppData\Roaming\Microsoft\Windows\Start Menu\Programs" directory in roaming, so maybe an advanced setting for that would be super?

I tested overriding the current file paths in the metadata.json from "yuzu-early-access*" to "C:\\Emulators\\Yuzu EA (Switch)*" in an attempt to add portability. The repair functionality does not appear to work with changing these paths. I tested by removing a Yuzu EA dll and seeing if it would repair it. The maintenance tool recreates the metadata.json and reinstalls yuzu-early-access wherever the tool is instead of looking in the new path and analyzing the files there, having moved the tool and supporting files to a completely different location.

Sorry for the wall of text, please let me know if I can clarify anything. I'm not skilled at Rust yet and I won't have much free time for a while, but I suppose I could take a stab at making a PR in the next month or so.

**Comment by MostlyWhat** [comment]
Go ahead with the PR and I will review it. School is currently taking most of my time right now. But try to put everything into bullet points so it's easier for implementation!

**Comment by MostlyWhat** [comment]
I will make a specific branch for this, but for also implementing other issues previously.

**Comment by MostlyWhat** [comment]
Implementing in #21
