### ISSUE TITLE
Installer deletes everything

### ISSUE THREAD

**Issue by steelpuxnastik** [MostlyWhat/128Bit-Yuzu-Installer#28]
I thought to use program simply like yuzu updater, because yuzu updater 1.5.1 do not work. So I just chose my folder with yuzu and games inside to, as I thought, update yuzu, but the program just deleted everything and created just another folder inside work emulator. Why it did such meanness when it could just only create that folder inside? I think it's radical bug, if you can fix that or just make loud warning that program will delete everything inside and user need to make backup or program can create it. But I do not remember anything from that.

**Comment by MostlyWhat** [comment]
Can you please take a look at #21. I am working on this, so now I have to create a warning during installation that it makes its own folder and stuff. I have school please just give me time.

P.S This is literally the same thing that the official yuzu uses.
