### ISSUE TITLE
Command line arguments for maintenance tool

### ISSUE THREAD

**Issue by LegzRwheelz** [MostlyWhat/128Bit-Yuzu-Installer#30]
I know this isn't an issue but is actually a question which I can't seem to get a definitive answer on. I've posted in Yuzu, Citra forums and subreddits but it's getting me nowhere as people are just pointing towards [This](https://github.com/yuzu-emu/yuzu/pull/5229) which is about the Yuzu exe, not the maintenance tool which is what my question is in regards to. I know that the Citra, Yuzu and Yuzu128bit installers are directly related to the maintenance tools I am wanting to automate and are basically the same thing, which is why I figured asking here may be more fruitful than asking in the emulator forums and subreddits.

Here's a copy/paste of my posts:

"Hey all, I have been creating tasks in task scheduler for silently updating my emulators, portable apps etc and I am now working on getting Yuzu and Citra implemented. As the previous statement suggests, I want to create a task in to run the maintenance tool nightly at 3am to check for and install updates so I am always running the latest and greatest. So, are there any command line arguments to update silently? Thanks in advance!!!!"

**Comment by MostlyWhat** [comment]
The maintainance tool wasn't supposed to be cli based, you can launch the shortcut and it will install and quit by itself. You can check out J-selby's liftinstaller as it was the code we used, there might be more info there. I might consider adding that to version 0.3 but there simply isn't enough demand for it. Message me on Discord if you need more info, I have the same username.
