### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by rwdsji** [MostlyWhat/128Bit-Yuzu-Installer#31]
Auto update functionality stopped working for me. My installation of Yuzu EA has been stuck at version 3507 for a couple of weeks now.

**Comment by akir42019** [comment]
you can download from here
https://github.com/pineappleEA/pineapple-src/releases

**Comment by golost2202** [comment]
Same for me the auto update seems to be broken, im stuck to Yuzu EA version 3507 like you @rwdsji.
It's not auto updating anymore

**Comment by MostlyWhat** [comment]
I know as our main contributor has quit and we don't have the source code anymore. Quick fix is incoming!
