### ISSUE TITLE
Windows gave bad result while creating shortcut: -2147024891

### ISSUE THREAD

**Issue by MiiArtisan** [MostlyWhat/128Bit-Yuzu-Installer#7]
started happening with the beta (im on windows 11 btw)
![image](https://user-images.githubusercontent.com/41709262/144928909-def8ebbb-a713-41a9-993b-3c3ee59bd2f5.png)

**Comment by MostlyWhat** [comment]
Take a look in the start folder and see if there is still the old shortcut. If so, delete it.

**Comment by MostlyWhat** [comment]
I will close this as there has not been any activity.
