### ISSUE TITLE
change folder warning 

### ISSUE THREAD

**Issue by pbanj** [MostlyWhat/128Bit-Yuzu-Installer#8]
![image](https://user-images.githubusercontent.com/17306233/150715481-30fbe46a-259c-46e1-a9ea-35e251a8aa4b.png)

you're deleting the contents. the pop up should say "this will delete all contents in this folder/directory" I'm glad i didn't select my documents folder or other anything with important stuff in it. i lost all my saves because of this.

**Comment by GlaZedBelmont** [comment]
overwrite = only the folder structure so if there are files in there, as long as they're not getting replaced by new files, they shouldn't get deleted.... which they do

It's making a new yuzu-windows-msvc folder in there (which yeah, the official one does that too but it will error out if it's not an empty folder, try running the maintenancetool.exe in %LOCALAPPDATA%/yuzu/, it won't work you need to move it out of the yuzu folder and delete the yuzu folder.)

I don't really know why you removed the warning but there should have been more preventions if you're gonna be clearing the folder it's installed to.

**Comment by GlaZedBelmont** [comment]
and yes, that could have cleared the entire emulators folder of pbanj if he hadn't made a folder just for yuzu. That's super dangerous

**Comment by MostlyWhat** [comment]
Can you summarise what I need to do. @pbanj @GlaZedBelmont

**Comment by MostlyWhat** [comment]
Implementing in #21
